/**
 * Content data for OS Installations and Activities
 * Add your YouTube video IDs and customize steps for each entry
 */

const OS_CONTENT = {
  win95: {
    title: 'Windows 95 Installation',
    description: 'Step-by-step guide to install Microsoft Windows 95.',
    videoId: 'YNka190U3mE',
    steps: [
      'Boot from the Windows 95 installation floppy or CD.',
      'Run setup.exe and follow the setup wizard.',
      'Choose the installation directory (default: C:\\WINDOWS).',
      'Select installation type (Typical, Portable, Compact, or Custom).',
      'Enter your name and optionally your company.',
      'Validate your product key.',
      'Complete the file copy and configuration process.',
      'Restart when prompted and finalize hardware detection.',
    ],
  },
  win98: {
    title: 'Windows 98 Installation',
    description: 'Complete guide for installing Windows 98.',
    videoId: 'OBDN08RCz9c',
    steps: [
      'Boot from the Windows 98 startup disk or CD.',
      'Run setup.exe from the CD or hard drive.',
      'Choose the installation directory.',
      'Select installation options and components.',
      'Enter your product key and complete setup.',
      'Restart and configure hardware as needed.',
    ],
  },
  '2000': {
    title: 'Windows 2000 Installation',
    description: 'Installing Windows 2000 Professional or Server.',
    videoId: 'DAJ84SYBRMk',
    steps: [
      'Boot from the Windows 2000 CD or create bootable media.',
      'Press Enter to set up Windows 2000.',
      'Accept the license agreement and specify installation partition.',
      'Choose to format the partition (NTFS recommended).',
      'Let setup copy files and restart.',
      'Complete the setup wizard (name, org, product key).',
      'Configure network and regional settings as prompted.',
    ],
  },
  me: {
    title: 'Windows ME Installation',
    description: 'Installing Windows Millennium Edition.',
    videoId: 'QZzh7DJOkj0',
    steps: [
      'Boot from the Windows ME CD or use setup from within Windows.',
      'Run setup.exe and follow the installation wizard.',
      'Accept the license and choose installation options.',
      'Enter product key and user information.',
      'Complete the setup and restart when prompted.',
    ],
  },
  nt: {
    title: 'Windows NT Installation',
    description: 'Installing Windows NT 4.0 Workstation or Server.',
    videoId: '6hDlvItX44o',
    steps: [
      'Boot from Windows NT installation disks or CD.',
      'Select installation options and target partition.',
      'Format the partition (NTFS or FAT).',
      'Copy files and configure hardware detection.',
      'Enter computer name, license mode, and administrator password.',
      'Configure network and complete setup.',
    ],
  },
  vista: {
    title: 'Windows Vista Installation',
    description: 'Installing Windows Vista with the setup wizard.',
    videoId: 'QqCWYtEaXus',
    steps: [
      'Boot from the Windows Vista DVD.',
      'Select language, time, and keyboard, then click Install now.',
      'Enter product key if you have one (or skip for trial).',
      'Choose the edition and accept the license terms.',
      'Select Custom installation and choose the partition.',
      'Wait for installation; the computer may restart several times.',
      'Complete the initial setup (user account, computer name, updates).',
    ],
  },
  xp: {
    title: 'Windows XP Installation',
    description: 'Classic guide to installing Windows XP.',
    videoId: 'qvHg7uo9T_4',
    steps: [
      'Boot from the Windows XP CD.',
      'Press Enter to set up Windows XP.',
      'Accept the license agreement and choose installation partition.',
      'Format the partition (NTFS recommended) and proceed.',
      'Let setup copy files and restart automatically.',
      'Complete the setup wizard (regional settings, name, product key).',
      'Configure network and finalize installation.',
    ],
  },
  server2003: {
    title: 'Windows Server 2003 Installation',
    description: 'Installing Windows Server 2003 Standard, Enterprise, or Web Edition.',
    videoId: 'Hnoph4s28w4',
    steps: [
      'Boot from the Windows Server 2003 CD.',
      'Follow the setup wizard; choose partition and format (NTFS).',
      'Enter product key and licensing mode (Per Seat or Per Server).',
      'Configure computer name and administrator password.',
      'Set date, time, and network settings.',
      'Join a workgroup or domain as desired.',
      'Complete setup and log in to configure roles.',
    ],
  },
  server2008: {
    title: 'Windows Server 2008 Installation',
    description: 'Installing Windows Server 2008 (or 2008 R2).',
    videoId: 'C5ReDjaDhhY',
    steps: [
      'Boot from the Windows Server 2008 DVD.',
      'Select language and click Install now.',
      'Choose edition (Standard, Enterprise, Datacenter) and type (Full or Core).',
      'Accept license and select Custom installation.',
      'Choose partition and proceed with installation.',
      'Set administrator password on first logon.',
      'Configure Server Manager and add roles as needed.',
    ],
  },
  win7: {
    title: 'Windows 7 Installation',
    description: 'Installing Windows 7 on your system.',
    videoId: 'U9W9IUOOPxA',
    steps: [
      'Boot from the Windows 7 DVD or USB.',
      'Select language and click Install now.',
      'Accept license terms and choose Custom installation.',
      'Select the drive/partition and proceed.',
      'Wait for installation; system will restart.',
      'Set up user account, computer name, and Windows Update.',
    ],
  },
  win8: {
    title: 'Windows 8 Installation',
    description: 'Installing Windows 8 or 8.1.',
    videoId: 'S2tD8sh7x9U',
    steps: [
      'Boot from Windows 8 media and start setup.',
      'Enter product key, accept license, choose Custom.',
      'Select partition and begin installation.',
      'After restarts, configure PC name, settings, and Microsoft account.',
    ],
  },
  win10: {
    title: 'Windows 10 Installation',
    description: 'Follow along with this comprehensive guide to install Windows 10 on your system.',
    videoId: 'niqZsuSfgB4',
    steps: [
      'Create a bootable USB drive using Microsoft\'s Media Creation Tool or Rufus.',
      'Enter your computer\'s BIOS/UEFI and set the USB drive as the primary boot device.',
      'Restart your computer and follow the Windows setup wizard prompts.',
      'Select your language, time zone, and keyboard layout.',
      'Click "Install now" and enter your product key (or choose "I don\'t have a product key").',
      'Select the edition of Windows 10 you want to install.',
      'Accept the license terms and choose "Custom: Install Windows only (advanced)".',
      'Select the drive/partition for installation and proceed with the setup.',
      'Wait for the installation to complete; your computer will restart several times.',
      'Complete the out-of-box experience (OOBE) setup for your account and preferences.',
    ],
  },
  win11: {
    title: 'Windows 11 Installation',
    description: 'Installing Windows 11 with TPM and Secure Boot requirements.',
    videoId: 'FJsZCE60Nzg',
    steps: [
      'Verify your PC meets Windows 11 requirements (TPM 2.0, Secure Boot).',
      'Create bootable USB using Media Creation Tool or Rufus.',
      'Boot from USB and start setup; select language and Install now.',
      'Enter product key or skip; choose Custom installation.',
      'Select partition and proceed with installation.',
      'Complete OOBE: Microsoft account, privacy settings, and preferences.',
    ],
  },
  server2012: {
    title: 'Windows Server 2012 Installation',
    description: 'Installing Windows Server 2012 or 2012 R2.',
    videoId: '9EBRROrw76k',
    steps: [
      'Boot from the Windows Server 2012 DVD.',
      'Select language and click Install now.',
      'Choose edition (Standard or Datacenter) and installation type.',
      'Accept license and select Custom installation.',
      'Choose partition and begin installation.',
      'Set administrator password and configure via Server Manager.',
    ],
  },
};

const ACTIVITIES_CONTENT = {
  'adding-users': {
    title: 'Adding Users',
    description: 'Learn how to add and manage user accounts in Windows Server 2008 Active Directory. This activity covers creating user accounts, setting passwords, and assigning users to groups for proper access control.',
    videoId: 'L0kBeGMx6so',
    steps: [
      'Open Active Directory Users and Computers (dsa.msc).',
      'Navigate to the desired Organizational Unit (OU).',
      'Right-click and select New → User.',
      'Enter user details (name, logon name, password).',
      'Set password options and create the account.',
      'Add the user to appropriate groups for permissions.',
    ],
  },
  dhcp: {
    title: 'DHCP Roles and Domain',
    description: 'This activity covers configuring DHCP (Dynamic Host Configuration Protocol) roles within a Windows Server 2008 environment and integrating with Active Directory Domain Services. You will learn how to install the DHCP server role, authorize the server in the domain, create scopes, and configure options for automatic IP address allocation to clients on your network.',
    videoId: 'pdy-10GAdC0',
    steps: [
      'Open Server Manager and add the DHCP Server role from the Add Roles Wizard.',
      'Authorize the DHCP server in Active Directory (if joined to a domain).',
      'Create a new IPv4 scope with the desired IP range and subnet mask.',
      'Configure scope options (default gateway, DNS servers, WINS if needed).',
      'Activate the scope and verify DHCP server operation.',
      'Test from a client by setting network adapter to obtain IP automatically.',
    ],
  },
  raid: {
    title: 'RAID Installations',
    description: 'Configure Redundant Array of Independent Disks (RAID) on Windows Server 2008. This activity demonstrates setting up RAID 0 (striping), RAID 1 (mirroring), or RAID 5 for improved performance and fault tolerance.',
    videoId: '_N_buGMdcO0',
    steps: [
      'Open Server Manager and add the File Services role with Storage Manager for SANs if needed.',
      'Use Disk Management to initialize new disks.',
      'Create a new striped (RAID 0), mirrored (RAID 1), or RAID-5 volume.',
      'Select the disks to include and assign drive letter.',
      'Format the volume and complete the wizard.',
    ],
  },
  'app-web': {
    title: 'Application and Web Server',
    description: 'Set up IIS (Internet Information Services) on Windows Server 2008 to host web applications. This activity covers installing the Web Server role, configuring sites, and application pools.',
    videoId: 'OzMg0zOdEOs',
    steps: [
      'Add the Web Server (IIS) role via Server Manager.',
      'Select required role services (ASP.NET, ISAPI, etc.).',
      'Create a new website or use the Default Web Site.',
      'Configure bindings, physical path, and permissions.',
      'Create application pools and assign applications.',
    ],
  },
  'file-server': {
    title: 'File Server',
    description: 'Deploy a file server role on Windows Server 2008 with shared folders, NTFS permissions, and share permissions for secure file access across the network.',
    videoId: 's4dmjefGT6Q',
    steps: [
      'Add the File Services role in Server Manager.',
      'Create shared folders and configure share permissions.',
      'Set NTFS permissions for fine-grained access control.',
      'Use the Share and Storage Management console for advanced options.',
      'Enable and configure quota management if desired.',
    ],
  },
  'group-policy': {
    title: 'Group Policy Management',
    description: 'Manage Group Policy Objects (GPOs) in Windows Server 2008 to control user and computer settings across the domain. Learn to create, edit, and apply GPOs to OUs.',
    videoId: 'xel6my4Swdc',
    steps: [
      'Open Group Policy Management Console (gpmc.msc).',
      'Create a new GPO or use an existing one.',
      'Edit the GPO and configure Computer/User settings.',
      'Link the GPO to the target OU.',
      'Set inheritance and enforcement options.',
      'Run gpupdate on clients to apply changes.',
    ],
  },
  wds: {
    title: 'Windows Deployment Services',
    description: 'Configure WDS to deploy Windows images over the network. This activity covers installing WDS, adding install and boot images, and deploying to clients via PXE boot.',
    videoId: 'Gy-HBaOWzi8',
    steps: [
      'Add the Windows Deployment Services role in Server Manager.',
      'Configure WDS server (choose Remote Installation folder).',
      'Add boot and install images from Windows installation media.',
      'Configure DHCP options (Option 60, 66, 67) if DHCP is on same server.',
      'Create capture images if building custom install images.',
      'Configure client computers to PXE boot and join the imaging process.',
    ],
  },
};
